### ISSUE TITLE
script/server won't start

### ISSUE THREAD

**Issue by mlainez** [mdarby/restful_acl#4]
Hello,

I installed the gem, added config.gem 'restful_acl' in my environment.rb, added the denied route but when I try to start my local server using script/server it fails throwing this :

/Library/Ruby/Gems/1.8/gems/restful_acl-3.0.3/lib/restful_acl/helper.rb:12: syntax error, unexpected ',', expecting '|' 
define_method("#{m}able?") do |*args, &block|

Am I missing something ?

Thanks

Marc

**Comment by mdarby** [comment]
Hate to say it, but everything works as expected in my test app. Can you post the full stack trace?

**Comment by darnellbrawner** [comment]
Same Issue

ruby script/console production
Loading production environment (Rails 2.3.5)
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in 'gem_original_require': /home/dbrawner/.gem/ruby/1.8/gems/restful_acl-3.0.3/lib/restful_acl/helper.rb:12: syntax error (SyntaxError)
      define_method("#{m}able?") do |*args, &block|
                                           ^
/home/dbrawner/.gem/ruby/1.8/gems/restful_acl-3.0.3/lib/restful_acl/helper.rb:13: syntax error
/home/dbrawner/.gem/ruby/1.8/gems/restful_acl-3.0.3/lib/restful_acl/helper.rb:24: syntax error  from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in 'require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:158:in 'require'
    from /home/dbrawner/.gem/ruby/1.8/gems/restful_acl-3.0.3/lib/restful_acl.rb:5
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in 'gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in 'require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:158:in `require'
from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:208:in 'load' 
from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in load_gems' ... 9 levels...
from /usr/lib/ruby/1.8/irb/init.rb:250:in 'load_modules'
from /usr/lib/ruby/1.8/irb/init.rb:21:in 'setup'
from /usr/lib/ruby/1.8/irb.rb:54:in 'start'
from /usr/bin/irb:13

**Comment by mdarby** [comment]
How do you guys include restful_acl? config.gem? Unpacked in /vendor/gems?
I've tested including via plugin, external gem and unpacked gem and cannot replicate.

Rails 2.3.4 & 2.3.5, Ruby 1.8.7 (2009-06-12 patchlevel 174)

Very odd as the failing snippet is perfectly valid Ruby...

**Comment by darnellbrawner** [comment]
ruby 1.8.5 rhel
rails 2.3.5
if i fire up irb and do a require 'rubygems' then require 'restful_acl' i get the same error

**Comment by mdarby** [comment]
```
irb(main):001:0> require 'rubygems'
=> false
irb(main):002:0> require 'restful_acl'
=> true
```

Again, I can't recreate this. Perhaps it's something to do with 1.8.5?

**Comment by LuisJoao** [comment]
It is not valid in 1.8.6

**Comment by mdarby** [comment]
Can you post the 1.8.6 valid version then?

**Comment by mdarby** [comment]
1.8.7 or better. Rails 3.0 requires it, so lets move forward.
