### ISSUE TITLE
Trying to put is_*able_by() into a module

### ISSUE THREAD

**Issue by arnekolja** [mdarby/restful_acl#6]
I am currently trying to put your is_indexable_by() (and so on) rules into a module, but I'm stuck at the problem, that I cannot access the calling object, because it isn't passed as an argument and self within a module always refers to the module itself, but not the object which it is implemented in.

Do you know how to get this done? Maybe a small demo snippet module would do the trick here...

This would make your plugin even more modular, as you can define ACLs globally without hardcoding it in each model :)

**Comment by arnekolja** [comment]
Uhm, think that one's obsolete. Didn't notice that not all of these methods are called on objects, sorry.

**Comment by WontSeeMeComin** [comment]
Hey, I just posted a question about this and didn't see your post. Did you figure out a way to keep this DRY?

**Comment by mdarby** [comment]
If this is still an issue, please see #8
